### PR TITLE
Remove expanded view on username on post

### LINKED ISSUE #3: Remove bubble overlay on username hover on tweets.
image
<br>
remove the expansion of username on hover and apply the linking to it directly.

### PR DESCRIPTION
**Pull request by imSyntn**
Fixed #3

Removed expanded view on username on post

Screenshot: 
Screenshot 2023-10-06 125828

### CODE REVIEW

**Comment by alanansari** [comment]
You had to remove the bubble appearing while hovering over the username on the posts.
Not fixed Yet.

**Comment by imSyntn** [comment]
ok. I am fixing this.

**Comment by imSyntn** [comment]
can you give me a screenshot of the issue

**Comment by alanansari** [comment]
> can you give me a screenshot of the issue

Sure.
image
I need this bubble removed while hovering over the username and the link to that profile to be there on the mention itself.

**Pull request closed without merging**
