### PR TITLE
Set website name in tab browser

### PR DESCRIPTION
**Pull request by tmatheas**
Website Name is set as the tab name.
Added a logo icon as 'T' to the tab icon

### CODE REVIEW

**Comment by alanansari** [comment]
Add favicon.ico as the tabicon.
Use the organisation logo for this purpose.

**Comment by tmatheas** [comment]
> Add favicon.ico as the tabicon. Use the organisation logo for this purpose.

Where is the organisation logo ?

**Comment by alanansari** [comment]
> > Add favicon.ico as the tabicon. Use the organisation logo for this purpose.
> 
> Where is the organisation logo ?
Screenshot 2023-10-08 001103

**Comment by tmatheas** [comment]
> > > Add favicon.ico as the tabicon. Use the organisation logo for this purpose.
> > 
> > 
> > Where is the organisation logo ?
> 
> Screenshot 2023-10-08 001103

Done @alanansari !!

**Comment by alanansari** [comment]
@tmatheas favicon isn't visible in the tab.. maybe the linking needs to be fixed.

**Comment by tmatheas** [comment]
> @tmatheas favicon isn't visible in the tab.. maybe the linking needs to be fixed.

Fixed the path @alanansari .

**Comment by alanansari** [comment]
@tmatheas Nice :)

**Comment by tmatheas** [comment]
@alanansari can you assign me for this issue?

**Pull request merged**
